import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const dictionary = {
    en: {
        // Navbar
        home: 'Home',
        aboutUs: 'About Us',
        signedInAs: 'Signed in as',
        changeName: 'Change Name',
        changePassword: 'Change Password',
        deleteAccount: 'Delete Account',
        about: 'About Us',
        ourSolutions: 'Our Solutions',
        contact: 'Contact',
        careers: 'Careers',

        // Home
        welcome_title: 'Take a Step for a Sustainable Future!',
        welcome_subtitle: 'Personal and Business Carbon Footprint Calculations - The Measure of Being Eco-Friendly',
        welcome_desc: 'Calculate your carbon footprint and learn what you can do to increase sustainability. Contribute to an eco-friendly future.',
        hero_btn_what_is: 'What is Carbon Footprint?',
        hero_btn_daily: 'My Daily Activities',

        section1_title: 'What is Carbon Footprint and Why is it Important?',
        section1_text: 'A carbon footprint is a metric system that measures the amount of greenhouse gases released into the atmosphere as a result of personal or business activities.',

        stat_avg_footprint: 'Global average carbon footprint per capita (tons CO2e)',
        stat_global_emission: "Global CO2 emission in 2019 (gigatonnes)",
        stat_net_zero_year: 'Target year for net zero emissions',

        feature1_title: 'Sustainability',
        feature1_desc: 'Secure tracking and management of carbon emissions',
        feature2_title: 'Emission Calculation',
        feature2_desc: 'Easy and accurate calculation of corporate emissions',
        feature3_title: 'User - Role',
        feature3_desc: 'Each user logs into the system with permissions appropriate to their role',
        feature4_title: 'Result Tracking',
        feature4_desc: 'Tracking the results of emission reduction measures',
        feature5_title: 'Reporting and Verification',
        feature5_desc: 'Reporting in international standards',
        feature6_title: 'Monitoring and Organization Process',
        feature6_desc: 'Direct and indirect emission calculation',

        // About
        about_title: 'About GreenTrack',
        about_mission: 'GreenTrack was founded with a simple yet powerful mission: to empower individuals to make a tangible difference in the fight against climate change through the simple act of planting and caring for trees and plants.',
        about_vision_desc: 'We believe that technology can bridge the gap between individual action and global impact. By tracking your plant collection, calculating carbon offsets, and connecting with a community of like-minded individuals, GreenTrack turns gardening into a global movement.',
        our_vision_title: 'Our Vision',
        our_vision_statement: 'A world where every individual is a steward of the environment, and where our collective green efforts actively restore the balance of our planet\'s ecosystem.',
        sustainability_first: 'Sustainability First',
        sustainability_desc: 'Every feature we build is designed to promote long-term ecological health.',
        community_driven: 'Community Driven',
        community_desc: 'We grow stronger together, sharing knowledge and celebrating milestones.',
        meet_designers: 'Meet Our Designers',
        lead_designer: 'Full Stack Developer',
        creative_director: 'Software Engineer',
        advisor: 'Advisor',

        full_stack_dev: 'Full Stack Developer',

        // Contact
        contact_title: 'Contact Us',
        contact_subtitle: 'We\'d love to hear from you. Send us a message below.',
        name_label: 'Name',
        name_placeholder: 'Your Name',
        email_label: 'Email',
        email_placeholder: 'your@email.com',
        subject_label: 'Subject',
        subject_placeholder: 'What is this regarding?',
        message_label: 'Message',
        message_placeholder: 'Your message here...',
        send_message_btn: 'Send Message',
        message_sent_title: 'Message Sent!',
        message_sent_desc: 'Thank you for reaching out. We\'ll get back to you shortly.',
        send_another_btn: 'Send another message',

        // Dashboard
        myPlants: 'My Plants',
        managePlants: 'Manage and track your plant collection.',
        addPlant: 'Add Plant',
        carbonReduction: 'Carbon Reduction',
        homeAtmosphere: "Home's Atmosphere",
        atmosphereGood: 'Good',
        atmosphereModerate: 'Moderate',
        atmospherePoor: 'Poor',
        emptyStateTitle: "You haven't added any plants yet.",
        emptyStateSubtitle: "Click the 'Add Plant' button to get started!",
        viewDetails: 'View Details',
        healthy: 'Healthy',
        needsWater: 'Needs Water',
        addPlantTitle: 'Add a New Plant',
        plantName: 'Plant Name',
        plantNamePlaceholder: 'e.g. My Rose',
        plantType: 'Plant Type',
        selectPlantType: 'Select a type…',
        typeOrSelectPlantType: 'Type or select a plant type…',
        addCustomType: 'Add new type:',
        noTypesFound: 'No types found',
        cancel: 'Cancel',
        saving: 'Saving…',
        save: 'Save',
        species: 'Species (Optional)',
        wateringFrequency: 'Watering Frequency (in days)',

        // Plant type name translations
        plantTypeNames: {
            'Monstera': 'Monstera',
            'Pothos': 'Pothos',
            'Snake Plant': 'Snake Plant',
            'Spider Plant': 'Spider Plant',
            'Peace Lily': 'Peace Lily',
            'Ficus': 'Ficus',
            'Orchid': 'Orchid',
            'Bonsai': 'Bonsai',
            'Aloe Vera': 'Aloe Vera',
            'Philodendron': 'Philodendron',
            'Calathea': 'Calathea',
            'Ivy': 'Ivy',
            'Jade Plant': 'Jade Plant',
            'ZZ Plant': 'ZZ Plant',
            'Begonia': 'Begonia',
            'Dracaena': 'Dracaena',
            'Tulip': 'Tulip',
            'Air Plant': 'Air Plant',
            'Bamboo': 'Bamboo',
            'Citrus Tree': 'Citrus Tree',
            'Cactus': 'Cactus',
            'Anthurium': 'Anthurium',
            'Dieffenbachia': 'Dieffenbachia',
            'Peperomia': 'Peperomia',
            'Croton': 'Croton',
            'Aglaonema': 'Aglaonema',
            'Chinese Money Plant': 'Chinese Money Plant',
            'Fittonia': 'Fittonia',
            'Syngonium': 'Syngonium',
            'Wax Plant': 'Wax Plant',
            'Tradescantia': 'Tradescantia',
            'Asparagus Fern': 'Asparagus Fern',
            'Bromeliad': 'Bromeliad',
            'Cast Iron Plant': 'Cast Iron Plant',
            'Parlor Palm': 'Parlor Palm',
            'Areca Palm': 'Areca Palm',
            'Ponytail Palm': 'Ponytail Palm',
            'Yucca': 'Yucca',
            'African Violet': 'African Violet',
            'Cyclamen': 'Cyclamen',
            'Kalanchoe': 'Kalanchoe',
            'Mint': 'Mint',
            'Basil': 'Basil',
            'Rosemary': 'Rosemary',
            'Lavender': 'Lavender',
            'Geranium': 'Geranium',
            'Hibiscus': 'Hibiscus',
            'Bougainvillea': 'Bougainvillea',
            'Chrysanthemum': 'Chrysanthemum',
            'Poinsettia': 'Poinsettia',
            'Fern': 'Fern',
            'Bird of Paradise': 'Bird of Paradise',
            'String of Pearls': 'String of Pearls',
            'String of Hearts': 'String of Hearts',
            'Money Tree': 'Money Tree',
            'Rubber Plant': 'Rubber Plant',
            'Lithops': 'Lithops',
            'Echeveria': 'Echeveria',
            'Haworthia': 'Haworthia',
            'Sedum': 'Sedum',
            'Pilea': 'Pilea',
            'Zamioculcas': 'Zamioculcas',
            'Maranta': 'Maranta',
            'Stromanthe': 'Stromanthe',
            'Alocasia': 'Alocasia',
            'Colocasia': 'Colocasia',
            'Caladium': 'Caladium',
            'Polyscias': 'Polyscias',
            'Schefflera': 'Schefflera',
            'Nephrolepis': 'Nephrolepis',
            'Asplenium': 'Asplenium',
            'Platycerium': 'Platycerium',
            'Adiantum': 'Adiantum',
            'Pteris': 'Pteris',
            'Blechnum': 'Blechnum',
            'Cycas': 'Cycas',
            'Rhapis': 'Rhapis',
            'Howea': 'Howea',
            'Phoenix': 'Phoenix',
            'Washingtonia': 'Washingtonia',
            'Caryota': 'Caryota',
            'Musa': 'Musa',
            'Strelitzia': 'Strelitzia',
            'Heliconia': 'Heliconia',
            'Canna': 'Canna',
            'Zingiber': 'Zingiber',
            'Curcuma': 'Curcuma',
            'Alpinia': 'Alpinia',
            'Costus': 'Costus',
            'Calathea Makoyana': 'Calathea Makoyana',
            'Ctenanthe': 'Ctenanthe',
            'Oxalis': 'Oxalis',
            'Senecio': 'Senecio',
            'Ceropegia': 'Ceropegia',
            'Dischidia': 'Dischidia',
            'Aeschynanthus': 'Aeschynanthus',
            'Columnea': 'Columnea',
            'Episcia': 'Episcia',
            'Streptocarpus': 'Streptocarpus',
            'Sinningia': 'Sinningia',
            'Primula': 'Primula',
            'Viola': 'Viola',
            'Petunia': 'Petunia',
            'Pelargonium': 'Pelargonium',
            'Fuchsia': 'Fuchsia',
            'Impatiens': 'Impatiens',
            'Begonia Maculata': 'Begonia Maculata',
            'Pachypodium': 'Pachypodium',
            'Adenium': 'Adenium',
            'Hoya': 'Hoya',
            'Araucaria': 'Araucaria',
            'Pachira': 'Pachira',
            'Rhoeo': 'Rhoeo',
            'Coleus': 'Coleus',
            'Iresine': 'Iresine',
            'Gynura': 'Gynura',
            'Hemigraphis': 'Hemigraphis',
        },

        // Footer
        mission: 'Measure Your Carbon Footprint, Leave a Mark on the Future',
        copyright: '© 2025 CarboonIT',
        platform: 'PLATFORM',
        corporate: 'CORPORATE',

        // Auth (Login/Signup/Forgot Password)
        welcome_back: 'Welcome Back',
        sign_in_subtitle: 'Sign in to your account',
        email_address_label: 'Email Address',
        password_label: 'Password',
        confirm_password_label: 'Confirm Password',
        remember_me: 'Remember me',
        forgot_password: 'Forgot password?',
        sign_in_btn: 'Login',
        no_account: "Don't have an account?",
        sign_up: 'Sign Up',
        create_account_title: 'Create Account',
        join_today: 'Join GreenTrack today',
        full_name_placeholder: 'Full Name',
        password_placeholder: 'Password',
        confirm_password_placeholder: 'Confirm Password',
        uploadPhoto: 'Upload Photo',
        photoTooLarge: 'Photo must be under 2 MB',
        create_account_btn: 'Create Account',
        already_have_account: 'Already have an account?',
        sign_in_link: 'Sign In',
        reset_password_title: 'Reset Password',
        reset_password_subtitle: 'Enter your email to receive a reset link',
        send_reset_link_btn: 'Send Reset Link',
        check_email_title: 'Check your email',
        check_email_desc: 'If an account exists for that email, we have sent password reset instructions.',
        back_to_login: 'Back to Login',
        logout: 'Logout',
        logoutConfirmTitle: 'Log Out?',
        logoutConfirmMessage: 'Are you sure you want to log out?',
        verify_code_title: 'Verify Code',
        verify_code_subtitle: 'Enter the 6-digit code sent to your email',
        verify_btn: 'Verify',
        new_password_title: 'Set New Password',
        new_password_subtitle: 'Enter your new password below',
        new_password_placeholder: 'New Password',
        reset_password_btn: 'Reset Password',
        password_reset_success: 'Password Reset Successful!',
        redirecting_to_login: 'Redirecting to login…',

        // Signup error/success messages
        error_email_registered: 'This email is already registered!',
        error_passwords_not_match: 'Passwords do not match!',
        error_server_connection: 'Could not connect to the server. Is Spring Boot running?',
        registration_success_title: 'Registration Successful!',
        redirecting_to_dashboard: 'Redirecting to your dashboard...',

        // --- NEW CORPORATE KEYS --- //
        corp_nav_home: 'Home',
        corp_nav_solutions: 'Solutions',
        corp_nav_calc: 'Calculations',
        corp_nav_skdm: 'SKDM',
        corp_nav_blog: 'Blog',
        corp_nav_contact: 'Contact',
        corp_nav_demo: 'Request Demo',
        corp_nav_login: 'Login',
        corp_nav_portal: 'Portal',
        corp_nav_logout: 'Logout',
        corp_nav_lang: 'Change Language',
        corp_portal_login: 'Portal Login',

        corp_hero_title_1: 'Take a Step for a',
        corp_hero_title_2: 'Sustainable Future!',
        corp_hero_subtitle: 'Personal and Business Carbon Footprint Calculations - The Measure of Being Eco-Friendly',
        corp_hero_desc: 'Calculate your carbon footprint and learn what you can do to increase sustainability. Contribute to an eco-friendly future.',
        corp_hero_btn_what_is: 'What is CarbonIT?',
        corp_hero_btn_daily: 'Demo',
        corp_what_is_carbonit_para1: "You can't reduce what you don't measure.\nReal change begins with data-driven awareness. At CarbonIT, we help individuals and organizations measure, report, and manage their carbon footprint — because a #sustainable #future isn't just about good intentions. It requires measurable action.",
        corp_what_is_carbonit_para2: "Green energy — solar, hydraulic, and wind power — slashes carbon footprints. With advancing technology, renewables offer cleaner, more accessible electricity, mitigate greenhouse gases, and stimulate local economies. Challenges remain, but innovation promises a #sustainable energy future. 🌍",
        corp_what_is_carbonit_point1: "📊 Turn data into action",
        corp_what_is_carbonit_point2: "♻️ Understand your impact — then reduce it",
        corp_what_is_carbonit_point3: "🌱 Take responsibility for the future",
        corp_what_is_carbonit_outro: "A small step you take today creates a big difference tomorrow.\nEmbrace #GreenEnergy for a smarter, cleaner tomorrow.",

        corp_intro_title: 'What is a Carbon Footprint and Why is it Important?',
        corp_intro_desc: 'A carbon footprint is a metric system that measures the amount of greenhouse gases released into the atmosphere from personal or business activities. Ensure correct analysis and reporting to minimize climate impact.',

        corp_feat_main_title: 'Advanced Features',
        corp_feat_main_desc: 'All the tools you need for your business to reach its sustainability goals in one platform.',

        corp_stat_title: 'Statistical Data on Carbon Footprint',
        corp_stat_desc: 'Explore global carbon footprint trends and understand how human activities affect our climate.',
        corp_stat_1_val: '4.8',
        corp_stat_1_desc: 'Average annual carbon emissions per capita (Tons)',
        corp_stat_2_val: '36.44',
        corp_stat_2_desc: 'Total carbon dioxide causing global warming (Billion Tons)',
        corp_stat_3_val: '2050',
        corp_stat_3_desc: 'Critical milestone year for the zero emissions target',

        corp_feat_num_title_1: 'Sustainability',
        corp_feat_num_desc_1: 'Minimize the environmental impact of your business with secure carbon emission tracking.',
        corp_feat_num_title_2: 'Emission Calculation',
        corp_feat_num_desc_2: 'Calculate corporate emissions easily and accurately at international standards.',
        corp_feat_num_title_3: 'User - Role',
        corp_feat_num_desc_3: 'Each user authenticates with role-appropriate permissions, ensuring secure access.',
        corp_feat_num_title_4: 'Result Tracking',
        corp_feat_num_desc_4: 'Instantly monitor and report the results of implemented emission reduction measures.',
        corp_feat_num_title_5: 'Reporting and Verification',
        corp_feat_num_desc_5: 'Report your carbon offset projects transparently at international standards.',
        corp_feat_num_title_6: 'Monitoring and Corporate Process',
        corp_feat_num_desc_6: 'Comprehensively monitor your organization\'s direct and indirect emission calculations.',

        corp_cta_title: 'Advantages of the Carbon Footprint Software',
        corp_cta_subtitle: 'Measure Your Carbon Footprint, Leave a Mark on the Future',
        corp_cta_placeholder: 'Enter your email address...',
        corp_cta_btn: 'Subscribe',
        corp_footer_newsletter: 'Stay up to date with CarboonIT.',
        corp_footer_newsletter_btn: 'Subscribe to Newsletter',

        corp_feat_img_main_title: 'Values Offered by Our System',
        corp_feat_img_desc_1: 'With CarboonIT, you can securely track and manage your organization\'s carbon emissions.',
        corp_feat_img_desc_2: 'You can easily and accurately calculate your corporate emissions using our embedded tools and routing interfaces.',
        corp_feat_img_desc_3: 'Each user logs in with role-based permissions and performs only authorized actions.',
        corp_feat_img_desc_4: 'Based on the calculation results, the organization can track mitigation efforts and project results natively in CarboonIT.',
        corp_feat_img_desc_5: 'With CarboonIT, standard carbon footprint calculations and verifications are processed within globally accepted legislation requirements.',
        corp_feat_img_desc_6: 'With CarboonIT, organizations can easily calculate and report direct and indirect emissions at the organization, process, and product levels.',

        corp_contact_subtitle: 'Talk to our expert team to crush your sustainability goals.',

        corp_page_sol_title: 'Our Corporate Solutions',
        corp_page_sol_desc: 'We offer tailored tools to minimize your business\'s environmental impact.',
        corp_page_skdm_title: 'CBAM (Carbon Border Adjustment Mechanism)',
        corp_page_skdm_desc: 'Detailed information on carbon reporting and compliance processes aligned with European Union standards.',
        corp_page_blog_title: 'Sustainability Diary',
        corp_page_blog_desc: 'The latest articles and insights on environmental technologies, green energy, and carbon reduction.',

        // ── Hero ──
        corp_hero_label: 'Carbon Tracking Platform',
        corp_hero_line1: 'Take Action For',
        corp_hero_line2: 'A Sustainable',
        corp_hero_line3: 'Future!',
        corp_hero_cta1: 'What is CarbonIT?',
        corp_hero_cta2: 'Demo',

        // ── Stats ──
        corp_stats_label: 'Statistics',
        corp_stats_sublabel: 'metrics & milestones',
        corp_stats_heading: 'Behind every statistic pulses a human story',
        corp_stats_subheading: 'Transforming industries, calculation by calculation',
        corp_stat_1_unit: 'ton CO2e',
        corp_stat_2_unit: 'Gt',
        corp_stat_4_desc: 'Customer satisfaction rate',

        // ── Services Accordion ──
        corp_svc_label: 'What We Do',
        corp_svc_sublabel: 'services',
        corp_svc_heading: 'Creative and technical expertise to amplify digital impact',
        corp_svc_title_1: 'Sustainability',
        corp_svc_desc_1: 'Securely track and manage your business\'s carbon emissions while minimizing environmental impact.',
        corp_svc_title_2: 'Emission Calculation',
        corp_svc_desc_2: 'Calculate emissions from your corporate activities with precision and ease.',
        corp_svc_title_3: 'CBAM Compliance',
        corp_svc_desc_3: 'Full compliance with the Carbon Border Adjustment Mechanism and EU standards.',
        corp_tag_karbon: 'Carbon Tracking',
        corp_tag_emisyon: 'Emission Reduction',
        corp_tag_raporlama: 'Reporting',
        corp_tag_ghg: 'GHG Protocol',
        corp_tag_kapsam: 'Scope 1-2-3',
        corp_tag_iso: 'ISO 14064',
        corp_tag_ab: 'EU Legislation',
        corp_tag_sertifika: 'Certification',
        corp_tag_dogrulama: 'Verification',
        corp_svc_link_projects: 'view our projects',
        corp_svc_link_plans: 'explore plans',

        // ── Bento Grid ──
        corp_bento_label: 'Why Us',
        corp_bento_sublabel: 'benefits',
        corp_bento_heading: 'Partnership, Not Just a Project',
        corp_bento_card1_title: 'Sustainability',
        corp_bento_card1_desc: 'Track and manage your carbon footprint with precision tools',
        corp_bento_card2_title: 'Emission Calculation',
        corp_bento_card2_desc: 'Accurate corporate emission reports and analysis',
        corp_bento_card3_desc: 'Emission Reduction',
        corp_bento_card4_title: 'User - Role Management',
        corp_bento_card5_title: 'Reporting & Verification',
        corp_bento_card6_title: 'Monitoring & Process',
        corp_bento_card6_desc: 'Direct and indirect emission tracking at organization level',

        // ── Process Steps ──
        corp_process_label: 'How It Works',
        corp_process_sublabel: 'process',
        corp_process_heading: 'Three steps to sustainability excellence',
        corp_process_title_1: 'Getting Started',
        corp_process_desc_1: 'Get up and running within 48 hours. Our team handles onboarding and initial data integration.',
        corp_process_title_2: 'Measurement & Analysis',
        corp_process_desc_2: 'Calculate your emissions accurately using industry-standard methodologies and our powerful tools.',
        corp_process_title_3: 'Reporting',
        corp_process_desc_3: 'Verification and reporting aligned with international standards and regulatory requirements.',

        // ── Testimonials ──
        corp_test_label: 'Client Stories',
        corp_test_sublabel: 'testimonials',
        corp_test_heading: 'Inspiring client experiences',
        corp_test_subheading: 'Join us and become our next success story',
        corp_test_quote_1: 'CarboonIT transformed how we approach sustainability. Their platform made emission tracking effortless and their team was incredibly responsive.',
        corp_test_name_1: 'Ayşe Yılmaz',
        corp_test_title_1: 'Sustainability Director',
        corp_test_company_1: 'EcoTech Solutions',
        corp_test_quote_2: 'The accuracy of their carbon calculations exceeded our expectations. We achieved our first verified carbon report in just two weeks.',
        corp_test_name_2: 'Mehmet Kaya',
        corp_test_title_2: 'Operations Manager',
        corp_test_company_2: 'GreenBuild Corp',
        corp_test_quote_3: 'The innovative approach and attention to compliance made all the difference. Our environmental reporting has never been this seamless.',
        corp_test_name_3: 'Elif Demir',
        corp_test_title_3: 'Environmental Analyst',
        corp_test_company_3: 'CleanAir Industries',
        corp_test_quote_4: 'CarboonIT\'s platform is exactly what we needed to meet EU carbon reporting requirements. Professional, precise, and powerful.',
        corp_test_name_4: 'Ali Öztürk',
        corp_test_title_4: 'CEO',
        corp_test_company_4: 'SustainTech',

        // ── Blog/Journal ──
        corp_journal_label: 'Blog',
        corp_journal_sublabel: 'latest',
        corp_journal_heading: 'Straight From the Newsroom',
        corp_blog_date_1: 'March 15, 2026',
        corp_blog_author_1: 'CarboonIT Team',
        corp_blog_title_1: 'Carbon Footprint Calculation Methods',
        corp_blog_excerpt_1: 'Understanding different methodologies for measuring your organization\'s carbon footprint and choosing the right approach.',
        corp_blog_date_2: 'March 1, 2026',
        corp_blog_author_2: 'CarboonIT Team',
        corp_blog_title_2: 'What is CBAM and How Does It Affect Businesses?',
        corp_blog_excerpt_2: 'A comprehensive guide to the Carbon Border Adjustment Mechanism and its implications for Turkish exporters.',
        corp_blog_date_3: 'February 15, 2026',
        corp_blog_author_3: 'CarboonIT Team',
        corp_blog_title_3: 'Sustainable Business Models',
        corp_blog_excerpt_3: 'How eco-conscious business practices are reshaping industries and creating competitive advantages.',
        corp_blog_date_4: 'February 1, 2026',
        corp_blog_author_4: 'CarboonIT Team',
        corp_blog_title_4: 'Reaching Net Zero 2050',
        corp_blog_excerpt_4: 'What businesses need to know about setting science-based targets and achieving net-zero commitments.',

        // ── CTA ──
        corp_cta_heading: 'We transform your brand. You\'re next.',
        corp_cta_subheading: 'Apply now for a one-on-one consultation with our experts.',
        corp_cta_btn_contact: 'Schedule a Meeting',
        corp_cta_btn_whatsapp: 'Write on WhatsApp',
        corp_cta_partners: 'Meet the partners who are part of our success story',

        // ── Footer ──
        corp_footer_location: 'Based in Ankara, Turkey.',
        corp_footer_timezone: 'GMT+3',
        corp_footer_nav_title: 'Navigation',
        corp_footer_newsletter_title: 'Stay in the Loop',
        corp_footer_email_placeholder: 'Your email address',
        corp_footer_rights_text: 'All rights reserved.',
        location_title: 'Location',
        corp_pricing_select: 'Select',
        corp_pricing_demo_req: 'Request Demo',
        // Demo Page Additions
        demo_title: "Request a Demo",
        demo_subtitle: "Experience our special software solution without purchasing. Fill out the form below to request your customized demo and explore environmental tracking tailored for your organization.",
        demo_name: "Full Name",
        demo_company: "Company Name",
        demo_email: "Corporate Email",
        demo_phone: "Corporate Phone",
        demo_promo: "Campaign Code (Optional)",
        demo_service: "Service You Are Interested In?",
        demo_kvkk: "I have read the clarification text under KVKK, I agree to the processing of my contact information.",
        demo_etk: "I have read the clarification text under ETK, I want to be informed about advertisements and announcements.",
        demo_submit: "SEND DEMO REQUEST",
    },
    tr: {
        // Navbar
        home: 'Ana Sayfa',
        aboutUs: 'Hakkımızda',
        signedInAs: 'Oturum açan:',
        changeName: 'İsim Değiştir',
        changePassword: 'Şifre Değiştir',
        deleteAccount: 'Hesabı Sil',
        about: 'Hakkımızda',
        ourSolutions: 'Çözümlerimiz',
        contact: 'İletişim',
        careers: 'Kariyer',

        // Home
        welcome_title: 'Sürdürülebilir Gelecek İçin Adım Atın!',
        welcome_subtitle: 'Kişisel ve İşletme Karbon Ayak İzi Hesaplamaları - Çevre Dostu Olmanın Ölçüsü',
        welcome_desc: 'Karbon ayak izinizi hesaplayın ve sürdürülebilirliği artırmak için neler yapabileceğinizi öğrenin. Çevre dostu bir gelecek için katkıda bulunun.',
        hero_btn_what_is: 'Karbon Ayak İzi Nedir?',
        hero_btn_daily: 'Gün İçinde Yaptıklarım',

        section1_title: 'Karbon Ayak İzi Nedir ve Neden Önemlidir?',
        section1_text: 'Karbon ayak izi, kişisel veya işletme faaliyetleri sonucu atmosfere salınan sera gazı miktarını ölçen bir metrik sistemdir.',

        stat_avg_footprint: 'Dünya genelinde kişi başına ortalama karbon ayak izi (ton CO2e)',
        stat_global_emission: "2019'da küresel CO2 emisyonu (gigaton)",
        stat_net_zero_year: 'Net sıfır emisyon hedef yılı',

        feature1_title: 'Sürdürülebilirlik',
        feature1_desc: 'Karbon salınımını güvenli takip ve yönetim',
        feature2_title: 'Emisyon Hesaplama',
        feature2_desc: 'Kurumsal emisyonları kolay ve doğru hesaplama',
        feature3_title: 'Kullanıcı - Rol',
        feature3_desc: 'Her kullanıcı kendi rolüne uygun yetkilerle sisteme giriş',
        feature4_title: 'Sonuç İzleme',
        feature4_desc: 'Emisyon azaltıcı önlemlerin sonuçlarını izleme',
        feature5_title: 'Raporlama ve Doğrulama',
        feature5_desc: 'Uluslararası standartlarda raporlama',
        feature6_title: 'İzleme ve Kuruluş Proses',
        feature6_desc: 'Doğrudan ve dolaylı emisyon hesaplama',

        // About
        about_title: 'GreenTrack Hakkında',
        about_mission: 'GreenTrack, basit ama güçlü bir misyonla kuruldu: bireyleri ağaç ve bitki dikip bakımını yaparak iklim değişikliğine karşı mücadelede somut bir fark yaratmaları için güçlendirmek.',
        about_vision_desc: 'Teknolojinin bireysel eylem ile küresel etki arasındaki boşluğu doldurabileceğine inanıyoruz. Bitki koleksiyonunuzu takip ederek, karbon denkleştirmelerini hesaplayarak ve benzer düşünen bireylerden oluşan bir toplulukla bağlantı kurarak GreenTrack, bahçeciliği küresel bir harekete dönüştürüyor.',
        our_vision_title: 'Vizyonumuz',
        our_vision_statement: 'Her bireyin çevrenin bir koruyucusu olduğu ve kolektif yeşil çabalarımızın gezegenimizin ekosisteminin dengesini aktif olarak onardığı bir dünya.',
        sustainability_first: 'Önce Sürdürülebilirlik',
        sustainability_desc: 'Oluşturduğumuz her özellik, uzun vadeli ekolojik sağlığı teşvik etmek için tasarlanmıştır.',
        community_driven: 'Topluluk Odaklı',
        community_desc: 'Birlikte güçleniyor, bilgiyi paylaşıyor ve dönüm noktalarını kutluyoruz.',
        meet_designers: 'Tasarımcılarımızla Tanışın',
        lead_designer: 'Full Stack Developer',
        creative_director: 'Software Engineer',
        advisor: 'Danışman',

        // Contact
        contact_title: 'Bize Ulaşın',
        contact_subtitle: 'Sizden haber almayı çok isteriz. Aşağıdan bize bir mesaj gönderin.',
        name_label: 'İsim',
        name_placeholder: 'İsminiz',
        email_label: 'E-posta',
        email_placeholder: 'senin@epostan.com',
        subject_label: 'Konu',
        subject_placeholder: 'Bu ne hakkında?',
        message_label: 'Mesaj',
        message_placeholder: 'Mesajınız...',
        send_message_btn: 'Mesaj Gönder',
        message_sent_title: 'Mesaj Gönderildi!',
        message_sent_desc: 'Bize ulaştığınız için teşekkürler. Kısa süre içinde size geri döneceğiz.',
        send_another_btn: 'Başka bir mesaj gönder',

        // Dashboard
        myPlants: 'Bitkilerim',
        managePlants: 'Bitki koleksiyonunuzu yönetin ve takip edin.',
        addPlant: 'Bitki Ekle',
        carbonReduction: 'Karbon Azaltımı',
        homeAtmosphere: 'Evin Hafası',
        atmosphereGood: 'İyi',
        atmosphereModerate: 'Orta',
        atmospherePoor: 'Kötü',
        emptyStateTitle: "Henüz hiç bitki eklemediniz.",
        emptyStateSubtitle: "Başlamak için 'Bitki Ekle' butonuna tıklayın!",
        viewDetails: 'Detayları Gör',
        healthy: 'Sağlıklı',
        needsWater: 'Su İhtiyacı Var',
        addPlantTitle: 'Yeni Bitki Ekle',
        plantName: 'Bitki Adı',
        plantNamePlaceholder: 'örn. Gülüm',
        plantType: 'Bitki Türü',
        selectPlantType: 'Bir tür seçin…',
        typeOrSelectPlantType: 'Bitki türü yazın veya seçin…',
        addCustomType: 'Yeni tür ekle:',
        noTypesFound: 'Tür bulunamadı',
        cancel: 'İptal',
        saving: 'Kaydediliyor…',
        save: 'Kaydet',
        species: 'Tür (İsteğe Bağlı)',
        wateringFrequency: 'Sulama Sıklığı (Gün Olarak)',

        // Plant type name translations
        plantTypeNames: {
            'Monstera': 'Deve Tabanı',
            'Pothos': 'Potos',
            'Snake Plant': 'Yılan Bitkisi',
            'Spider Plant': 'Örümcek Bitkisi',
            'Peace Lily': 'Barış Zambağı',
            'Ficus': 'Kauçuk Ağacı',
            'Orchid': 'Orkide',
            'Bonsai': 'Bonsai',
            'Aloe Vera': 'Aloe Vera',
            'Philodendron': 'Filodendron',
            'Calathea': 'Kalatea',
            'Ivy': 'Sarmaşık',
            'Jade Plant': 'Para Çiçeği',
            'ZZ Plant': 'ZZ Bitkisi',
            'Begonia': 'Begonya',
            'Dracaena': 'Drasena',
            'Tulip': 'Lale',
            'Air Plant': 'Hava Bitkisi',
            'Bamboo': 'Bambu',
            'Citrus Tree': 'Narenciye Ağacı',
            'Cactus': 'Kaktüs',
            'Anthurium': 'Flamingo Çiçeği',
            'Dieffenbachia': 'Difenbahya',
            'Peperomia': 'Zümrüt Dalı',
            'Croton': 'Kroton',
            'Aglaonema': 'Çin Herdemyeşili',
            'Chinese Money Plant': 'Çin Para Çiçeği',
            'Fittonia': 'Mozaik Çiçeği',
            'Syngonium': 'Melek Kanadı',
            'Wax Plant': 'Mum Çiçeği',
            'Tradescantia': 'Telgraf Çiçeği',
            'Asparagus Fern': 'Kuşkonmaz Eğreltisi',
            'Bromeliad': 'Bromelya',
            'Cast Iron Plant': 'Salon Yaprağı',
            'Parlor Palm': 'Dağ Palmiyesi',
            'Areca Palm': 'Areka Palmiyesi',
            'Ponytail Palm': 'Fil Ayağı',
            'Yucca': 'Yuka',
            'African Violet': 'Afrika Menekşesi',
            'Cyclamen': 'Sıklamen',
            'Kalanchoe': 'Kalanşo',
            'Mint': 'Nane',
            'Basil': 'Fesleğen',
            'Rosemary': 'Biberiye',
            'Lavender': 'Lavanta',
            'Geranium': 'Sardunya',
            'Hibiscus': 'Japon Gülü',
            'Bougainvillea': 'Begonvil',
            'Chrysanthemum': 'Kasımpatı',
            'Poinsettia': 'Atatürk Çiçeği',
            'Fern': 'Eğrelti Otu',
            'Bird of Paradise': 'Cennet Kuşu Çiçeği',
            'String of Pearls': 'İnci Kolyesi',
            'String of Hearts': 'Kalp Kalbe Karşı',
            'Money Tree': 'Para Ağacı',
            'Rubber Plant': 'Kauçuk Ağacı',
            'Lithops': 'Yaşayan Taşlar',
            'Echeveria': 'Eçeverya',
            'Haworthia': 'Yılan Derisi Çiçeği',
            'Sedum': 'Damkoruğu',
            'Pilea': 'Pilea',
            'Zamioculcas': 'Zeze Çiçeği',
            'Maranta': 'Dua Çiçeği',
            'Stromanthe': 'Stromante',
            'Alocasia': 'Fil Kulağı',
            'Colocasia': 'Kolokazya',
            'Caladium': 'Kaladyum',
            'Polyscias': 'Aralya',
            'Schefflera': 'Şeflera',
            'Nephrolepis': 'Aşk Merdiveni',
            'Asplenium': 'Kuş Yuvası Eğreltisi',
            'Platycerium': 'Geyik Boynuzu Eğreltisi',
            'Adiantum': 'Venüs Saçı',
            'Pteris': 'Pteris',
            'Blechnum': 'Blechnum',
            'Cycas': 'Sago Palmiyesi',
            'Rhapis': 'Bambu Palmiyesi',
            'Howea': 'Kentia Palmiyesi',
            'Phoenix': 'Hurma Palmiyesi',
            'Washingtonia': 'Washington Palmiyesi',
            'Caryota': 'Balık Kuyruğu Palmiyesi',
            'Musa': 'Muz Ağacı',
            'Strelitzia': 'Starliçe',
            'Heliconia': 'Helikonya',
            'Canna': 'Tesbih Çiçeği',
            'Zingiber': 'Zencefil',
            'Curcuma': 'Zerdeçal',
            'Alpinia': 'Alpinya',
            'Costus': 'Kostus',
            'Calathea Makoyana': 'Tavus Kuşu Çiçeği',
            'Ctenanthe': 'Ctenanthe',
            'Oxalis': 'Uyku Çiçeği',
            'Senecio': 'İnci Tanesi',
            'Ceropegia': 'Kalp Kalbe',
            'Dischidia': 'Karınca Bitkisi',
            'Aeschynanthus': 'Ruj Çiçeği',
            'Columnea': 'Japon Balığı Çiçeği',
            'Episcia': 'Episcia',
            'Streptocarpus': 'Streptocarpus',
            'Sinningia': 'Bardak Menekşesi',
            'Primula': 'Çuha Çiçeği',
            'Viola': 'Hercai Menekşe',
            'Petunia': 'Petunya',
            'Pelargonium': 'Sakız Sardunya',
            'Fuchsia': 'Küpe Çiçeği',
            'Impatiens': 'Cam Güzeli',
            'Begonia Maculata': 'Çilli Begonya',
            'Pachypodium': 'Madagaskar Palmiyesi',
            'Adenium': 'Çöl Gülü',
            'Hoya': 'Hoya Çiçeği',
            'Araucaria': 'Salon Çamı',
            'Pachira': 'Para Ağacı',
            'Rhoeo': 'Musa’nın Beşiği',
            'Coleus': 'Kolyos',
            'Iresine': 'Kırmızı Yapraklı Kan Çiçeği',
            'Gynura': 'Kadife Çiçeği',
            'Hemigraphis': 'Mor İnci',
        },

        // Footer
        mission: 'Karbon Ayak İzinizi Ölçün, Geleceğe İz Bırakın',
        copyright: '© 2025 CarboonIT',
        platform: 'PLATFORM',
        corporate: 'KURUMSAL',

        // Auth (Login/Signup/Forgot Password)
        welcome_back: 'Tekrar Hoş Geldiniz',
        sign_in_subtitle: 'Hesabınıza giriş yapın',
        email_address_label: 'E-posta Adresi',
        password_label: 'Şifre',
        confirm_password_label: 'Şifreyi Onayla',
        remember_me: 'Beni Hatırla',
        forgot_password: 'Şifremi Unuttum?',
        sign_in_btn: 'Giriş Yap',
        no_account: 'Hesabınız yok mu?',
        sign_up: 'Kayıt Ol',
        create_account_title: 'Hesap Oluştur',
        join_today: 'Bugün GreenTrack\'e Katılın',
        full_name_placeholder: 'Tam İsim',
        password_placeholder: 'Şifre',
        confirm_password_placeholder: 'Şifreyi Onayla',
        uploadPhoto: 'Fotoğraf Yükle',
        photoTooLarge: 'Fotoğraf 2 MB\u0027dan küçük olmalıdır',
        create_account_btn: 'Hesap Oluştur',
        already_have_account: 'Zaten bir hesabınız var mı?',
        sign_in_link: 'Giriş Yap',
        reset_password_title: 'Şifreyi Sıfırla',
        reset_password_subtitle: 'Sıfırlama bağlantısı almak için e-postanızı girin',
        send_reset_link_btn: 'Sıfırlama Bağlantısı Gönder',
        check_email_title: 'E-postanızı kontrol edin',
        check_email_desc: 'Eğer bu e-posta adresiyle bir hesap varsa, şifre sıfırlama talimatlarını gönderdik.',
        back_to_login: 'Girişe Dön',
        logout: 'Çıkış Yap',
        logoutConfirmTitle: 'Çıkış Yap?',
        logoutConfirmMessage: 'Çıkış yapmak istediğinizden emin misiniz?',
        verify_code_title: 'Kodu Doğrulayın',
        verify_code_subtitle: 'E-postanıza gönderilen 6 haneli kodu girin',
        verify_btn: 'Doğrula',
        new_password_title: 'Yeni Şifre Belirleyin',
        new_password_subtitle: 'Yeni şifrenizi aşağıya girin',
        new_password_placeholder: 'Yeni Şifre',
        reset_password_btn: 'Şifreyi Sıfırla',
        password_reset_success: 'Şifre Sıfırlama Başarılı!',
        redirecting_to_login: 'Giriş sayfasına yönlendiriliyorsunuz…',

        // Signup error/success messages
        error_email_registered: 'Bu e-posta zaten kayıtlı!',
        error_passwords_not_match: 'Şifreler eşleşmiyor!',
        error_server_connection: 'Sunucuya bağlanılamadı. Spring Boot çalışıyor mu?',
        registration_success_title: 'Kayıt Başarılı!',
        redirecting_to_dashboard: 'Panele yönlendiriliyorsunuz...',

        // --- NEW CORPORATE KEYS --- //
        corp_nav_home: 'Anasayfa',
        corp_nav_solutions: 'Çözümler',
        corp_nav_calc: 'Hesaplama',
        corp_nav_skdm: 'SKDM',
        corp_nav_blog: 'Blog',
        corp_nav_contact: 'İletişim',
        corp_nav_demo: 'Demo Talebi',
        corp_nav_login: 'Giriş Yap',
        corp_nav_portal: 'Portal',
        corp_nav_logout: 'Çıkış Yap',
        corp_nav_lang: 'Dil Değiştir',
        corp_portal_login: 'Portal Giriş',

        corp_hero_title_1: 'Sürdürülebilir Gelecek İçin',
        corp_hero_title_2: 'Adım Atın!',
        corp_hero_subtitle: 'Kişisel ve İşletme Karbon Ayak İzi Hesaplamaları - Çevre Dostu Olmanın Ölçüsü',
        corp_hero_desc: 'Karbon ayak izinizi hesaplayın ve sürdürülebilirliği artırmak için neler yapabileceğinizi öğrenin. Çevre dostu bir gelecek için katkıda bulunun.',
        corp_hero_btn_what_is: 'CarbonIT Nedir?',
        corp_hero_btn_daily: 'Demo',
        corp_what_is_carbonit_para1: "Ölçemediğiniz şeyi azaltamazsınız.\nGerçek değişim, veriye dayalı farkındalıkla başlar. CarbonIT olarak, bireylerin ve kurumların karbon ayak izlerini ölçmelerine, raporlamalarına ve yönetmelerine yardımcı oluyoruz — çünkü #sürdürülebilir bir #gelecek sadece iyi niyetlerle inşa edilemez. Ölçülebilir eylemler gerektirir.",
        corp_what_is_carbonit_para2: "Yeşil enerji — güneş, hidroelektrik ve rüzgar gücü — karbon ayak izlerini büyük ölçüde azaltır. Gelişen teknolojiyle birlikte yenilenebilir enerji daha temiz ve erişilebilir elektrik sunarak sera gazlarını hafifletir ve yerel ekonomileri canlandırır. Zorluklar devam etse de, inovasyon #sürdürülebilir bir enerji geleceği vaat ediyor. 🌍",
        corp_what_is_carbonit_point1: "📊 Veriyi eyleme dönüştürün",
        corp_what_is_carbonit_point2: "♻️ Etkinizi anlayın — sonra azaltın",
        corp_what_is_carbonit_point3: "🌱 Gelecek için sorumluluk alın",
        corp_what_is_carbonit_outro: "Bugün atacağınız küçük bir adım, yarın büyük bir fark yaratır.\nDaha akıllı, daha temiz bir yarın için #YeşilEnerji'yi benimseyin.",

        corp_intro_title: 'Karbon Ayak İzi Nedir ve\nNeden Önemlidir?',
        corp_intro_desc: 'Karbon ayak izi, kişisel veya işletme faaliyetleri sonucu atmosfere salınan sera gazı miktarını ölçen bir metrik sistemdir. Doğru analiz ve raporlama ile iklim değişikliğinin etkilerini en aza indirebilirsiniz.',

        corp_feat_main_title: 'Gelişmiş Özellikler',
        corp_feat_main_desc: 'İşletmenizin sürdürülebilirlik hedeflerine ulaşması için ihtiyacınız olan tüm araçlar tek platformda.',

        corp_stat_title: 'Karbon Ayak İzi Hakkında İstatistiksel Veriler',
        corp_stat_desc: 'Farklı ülkelerin karbon ayak izi verilerini toplayın ve bu verileri analiz ederek karşılaştırmalar yapın. Dünya genelindeki karbon ayak izi eğilimlerini ve trendleri inceleyerek, insan faaliyetlerinin çevreye olan etkisini göstermeyi amaçlıyoruz.',
        corp_stat_1_val: '4.8',
        corp_stat_1_desc: 'Kişi başı ortalama yıllık karbon salınımı (Ton)',
        corp_stat_2_val: '36.44',
        corp_stat_2_desc: 'Küresel ısınmaya neden olan toplam karbondioksit (Milyar Ton)',
        corp_stat_3_val: '2050',
        corp_stat_3_desc: 'Sıfır emisyon hedefi için kritik dönüm noktası yılı',

        corp_feat_num_title_1: 'Sürdürülebilirlik',
        corp_feat_num_desc_1: 'Karbon salınımını güvenli takip ve yönetim ile işletmenizin çevresel etkisini en aza indirin.',
        corp_feat_num_title_2: 'Emisyon Hesaplama',
        corp_feat_num_desc_2: 'Kurumsal emisyonları uluslararası standartlarda kolay ve eşsiz bir doğrulukla hesaplayın.',
        corp_feat_num_title_3: 'Kullanıcı - Rol',
        corp_feat_num_desc_3: 'Her kullanıcı kendi rolüne uygun yetkilerle sisteme giriş yaparak güvenli erişim sağlar.',
        corp_feat_num_title_4: 'Sonuç İzleme',
        corp_feat_num_desc_4: 'Uygulanan emisyon azaltıcı önlemlerin sonuçlarını anlık olarak izleyin ve raporlayın.',
        corp_feat_num_title_5: 'Raporlama ve Doğrulama',
        corp_feat_num_desc_5: 'Karbon denkleştirme projelerinizi uluslararası standartlarda şeffaf bir şekilde raporlayın.',
        corp_feat_num_title_6: 'İzleme ve Kuruluş Proses',
        corp_feat_num_desc_6: 'Kuruluşunuzun doğrudan ve dolaylı emisyon hesaplamalarını kapsamlı bir şekilde izleyin.',

        corp_cta_title: 'Karbon Ayak İzi Hesaplama Yöntemleri',
        corp_cta_subtitle: 'Karbon ayak izinizi hesaplayın ve sürdürülebilirliği artırmak için neler yapabileceğinizi öğrenin. Çevre dostu bir gelecek için katkıda bulunun.',
        corp_cta_placeholder: 'E-posta adresinizi girin...',
        corp_cta_btn: 'Abone Ol',
        corp_footer_newsletter: 'CarboonIT haberin olsun.',
        corp_footer_newsletter_btn: 'Bültene Kaydol',

        corp_feat_img_main_title: 'Sistemimizin Sunduğu Değerler',
        corp_feat_img_desc_1: 'CarboonIT ile kuruluşunuzun ürettiği karbon salınımını güvenli bir şekilde takip edip yönetebilirsiniz.',
        corp_feat_img_desc_2: 'Uygulama içerisinde bulunan arayüzler ve yönlendirme araçları ile kurumsal faaliyetlerinize yönelik emisyonları hem kolayca hem de en doğru şekilde hesaplayabilirsiniz.',
        corp_feat_img_desc_3: 'Her kullanıcı kendi rolüne uygun yetkilerle sisteme giriş yapmakta ve sadece yetkili olduğu işlemleri gerçekleştirebilmektedir.',
        corp_feat_img_desc_4: 'Hesaplama sonuçlarına göre kuruluş tarafından uygulanan emisyon azaltıcı önlemler ve yürütülen projelerin de sonuçları CarboonIT üzerinden izlenebilmektedir.',
        corp_feat_img_desc_5: 'CarboonIT ile, bireylerin, şirketlerin ve kurumların karbon ayak izlerinin dünyada kabul görmüş mevzuat ve standartlar çerçevesinde hesaplanması, raporlanması ve doğrulanması işlemlerinin yapılması gerçekleştirilir.',
        corp_feat_img_desc_6: 'CarboonIT ile kuruluş, proses ve ürün bazında oluşan doğrudan ve dolaylı emisyonlarını kolay bir şekilde güncel mevzuata göre hesaplayarak raporlayabilmektedir.',

        corp_contact_subtitle: 'Sürdürülebilirlik hedeflerinize ulaşmak için uzman ekibimizle görüşün.',

        corp_page_sol_title: 'Kurumsal Çözümlerimiz',
        corp_page_sol_desc: 'İşletmenizin çevresel etkisini en aza indirmek için özelleştirilmiş araçlar sunuyoruz.',
        corp_page_skdm_title: 'SKDM (Sınırda Karbon Düzenleme Mekanizması)',
        corp_page_skdm_desc: 'Avrupa Birliği standartlarına uygun karbon raporlama ve uyum süreçleri hakkında detaylı bilgi.',
        corp_page_blog_title: 'Sürdürülebilirlik Günlüğü',
        corp_page_blog_desc: 'Çevre teknolojileri, yeşil enerji ve karbon azaltımı üzerine en güncel makaleler ve içgörüler.',

        corp_footer_desc: 'Sürdürülebilir bir gelecek için yenilikçi karbon ayak izi hesaplama ve yönetim çözümleri.',
        corp_footer_quick_links: 'Hızlı Bağlantılar',
        corp_footer_rights: '© 2025 CarboonIT. Tüm hakları saklıdır.',
        corp_coming_soon: 'İçerik yakında eklenecektir.',

        // ── Hero ──
        corp_hero_label: 'Karbon Takip Platformu',
        corp_hero_line1: 'Sürdürülebilir',
        corp_hero_line2: 'Gelecek İçin',
        corp_hero_line3: 'Adım Atın!',
        corp_hero_cta1: 'CarbonIT Nedir?',
        corp_hero_cta2: 'Demo',

        // ── Stats ──
        corp_stats_label: 'İstatistikler',
        corp_stats_sublabel: 'metrikler & kilometre taşları',
        corp_stats_heading: 'Her istatistiğin arkasında bir insan hikayesi var',
        corp_stats_subheading: 'Endüstrileri dönüştürüyoruz, hesaplama hesaplama',
        corp_stat_1_unit: 'ton CO2e',
        corp_stat_2_unit: 'Gt',
        corp_stat_4_desc: 'Müşteri memnuniyet oranı',

        // ── Services Accordion ──
        corp_svc_label: 'Ne Yapıyoruz',
        corp_svc_sublabel: 'hizmetler',
        corp_svc_heading: 'Dijital etkiyi artırmak için yaratıcı ve teknik uzmanlık',
        corp_svc_title_1: 'Sürdürülebilirlik',
        corp_svc_desc_1: 'Karbon salınımını güvenli bir şekilde takip edip yönetin ve çevresel etkiyi en aza indirin.',
        corp_svc_title_2: 'Emisyon Hesaplama',
        corp_svc_desc_2: 'Kurumsal faaliyetlerinize yönelik emisyonları hassas ve kolay bir şekilde hesaplayın.',
        corp_svc_title_3: 'SKDM Uyum',
        corp_svc_desc_3: 'Sınırda Karbon Düzenleme Mekanizması ve AB standartlarına tam uyum.',
        corp_tag_karbon: 'Karbon Takip',
        corp_tag_emisyon: 'Emisyon Azaltma',
        corp_tag_raporlama: 'Raporlama',
        corp_tag_ghg: 'GHG Protokolü',
        corp_tag_kapsam: 'Kapsam 1-2-3',
        corp_tag_iso: 'ISO 14064',
        corp_tag_ab: 'AB Mevzuatı',
        corp_tag_sertifika: 'Sertifikasyon',
        corp_tag_dogrulama: 'Doğrulama',
        corp_svc_link_projects: 'projelerimizi gör',
        corp_svc_link_plans: 'planları keşfet',

        // ── Bento Grid ──
        corp_bento_label: 'Neden Biz',
        corp_bento_sublabel: 'avantajlar',
        corp_bento_heading: 'Proje Değil, Ortaklık',
        corp_bento_card1_title: 'Sürdürülebilirlik',
        corp_bento_card1_desc: 'Hassas araçlarla karbon ayak izinizi takip edin ve yönetin',
        corp_bento_card2_title: 'Emisyon Hesaplama',
        corp_bento_card2_desc: 'Doğru kurumsal emisyon raporları ve analizler',
        corp_bento_card3_desc: 'Emisyon Azaltma',
        corp_bento_card4_title: 'Kullanıcı - Rol Yönetimi',
        corp_bento_card5_title: 'Raporlama ve Doğrulama',
        corp_bento_card6_title: 'İzleme ve Kuruluş Proses',
        corp_bento_card6_desc: 'Kuruluş düzeyinde doğrudan ve dolaylı emisyon takibi',

        // ── Process Steps ──
        corp_process_label: 'Nasıl Çalışır',
        corp_process_sublabel: 'süreç',
        corp_process_heading: 'Sürdürülebilirlik mükemmelliğine üç adım',
        corp_process_title_1: 'Başlangıç',
        corp_process_desc_1: '48 saat içinde aksiyona geçin. Ekibimiz başlangıç sürecini ve veri entegrasyonunu yönetir.',
        corp_process_title_2: 'Ölçüm & Analiz',
        corp_process_desc_2: 'Emisyonlarınızı endüstri standardı metodolojiler ve güçlü araçlarımızla doğru hesaplayın.',
        corp_process_title_3: 'Raporlama',
        corp_process_desc_3: 'Uluslararası standartlar ve düzenleyici gerekliliklere uyumlu doğrulama ve raporlama.',

        // ── Testimonials ──
        corp_test_label: 'Müşteri Hikayeleri',
        corp_test_sublabel: 'referanslar',
        corp_test_heading: 'İlham veren müşteri deneyimleri',
        corp_test_subheading: 'Bize katılın ve bir sonraki başarı hikayemiz olun',
        corp_test_quote_1: 'CarboonIT sürdürülebilirliğe yaklaşım şeklimizi dönüştürdü. Platformları emisyon takibini zahmetsiz hale getirdi.',
        corp_test_name_1: 'Ayşe Yılmaz',
        corp_test_title_1: 'Sürdürülebilirlik Direktörü',
        corp_test_company_1: 'EcoTech Solutions',
        corp_test_quote_2: 'Karbon hesaplamalarının doğruluğu beklentilerimizi aştı. İlk doğrulanmış raporumuzu iki haftada aldık.',
        corp_test_name_2: 'Mehmet Kaya',
        corp_test_title_2: 'Operasyon Müdürü',
        corp_test_company_2: 'GreenBuild Corp',
        corp_test_quote_3: 'Yenilikçi yaklaşım ve uyumluluk hassasiyeti büyük fark yarattı. Raporlamamız hiç bu kadar kusursuz olmamıştı.',
        corp_test_name_3: 'Elif Demir',
        corp_test_title_3: 'Çevre Analisti',
        corp_test_company_3: 'CleanAir Industries',
        corp_test_quote_4: 'CarboonIT\'in platformu AB karbon raporlama gereklilikleri için tam ihtiyacımız olan şeydi.',
        corp_test_name_4: 'Ali Öztürk',
        corp_test_title_4: 'CEO',
        corp_test_company_4: 'SustainTech',

        // ── Blog/Journal ──
        corp_journal_label: 'Blog',
        corp_journal_sublabel: 'güncel',
        corp_journal_heading: 'Haberlerden Direkt',
        corp_blog_date_1: '15 Mart 2026',
        corp_blog_author_1: 'CarboonIT Ekibi',
        corp_blog_title_1: 'Karbon Ayak İzi Hesaplama Yöntemleri',
        corp_blog_excerpt_1: 'Kuruluşunuzun karbon ayak izini ölçmek için farklı metodolojileri anlamak ve doğru yaklaşımı seçmek.',
        corp_blog_date_2: '1 Mart 2026',
        corp_blog_author_2: 'CarboonIT Ekibi',
        corp_blog_title_2: 'SKDM Nedir ve İşletmeleri Nasıl Etkiler?',
        corp_blog_excerpt_2: 'Sınırda Karbon Düzenleme Mekanizması ve Türk ihracatçıları üzerindeki etkileri hakkında kapsamlı rehber.',
        corp_blog_date_3: '15 Şubat 2026',
        corp_blog_author_3: 'CarboonIT Ekibi',
        corp_blog_title_3: 'Sürdürülebilir İş Modelleri',
        corp_blog_excerpt_3: 'Çevre dostu iş uygulamalarının endüstrileri nasıl yeniden şekillendirdiği ve rekabet avantajları yarattığı.',
        corp_blog_date_4: '1 Şubat 2026',
        corp_blog_author_4: 'CarboonIT Ekibi',
        corp_blog_title_4: '2050 Net Sıfır Hedefine Ulaşmak',
        corp_blog_excerpt_4: 'Bilim temelli hedefler belirlemek ve net sıfır taahhütlerini yerine getirmek için işletmelerin bilmesi gerekenler.',

        // ── CTA ──
        corp_cta_heading: 'Markanızı dönüştürüyoruz. Sıra sizde.',
        corp_cta_subheading: 'Uzmanlarımızla birebir görüşme için hemen başvurun.',
        corp_cta_btn_contact: 'Görüşme Planla',
        corp_cta_btn_whatsapp: 'WhatsApp\'tan Yaz',
        corp_cta_partners: 'Başarı hikayemizin parçası olan ortaklarımızla tanışın',

        // ── Footer ──
        corp_footer_location: 'Ankara, Türkiye\'de konuşlandık.',
        corp_footer_timezone: 'GMT+3',
        corp_footer_nav_title: 'Navigasyon',
        corp_footer_newsletter_title: 'Haberdar Olun',
        corp_footer_email_placeholder: 'E-posta adresiniz',
        corp_footer_rights_text: 'Tüm hakları saklıdır.',
        location_title: 'Konum',
        corp_pricing_select: 'Seç',
        corp_pricing_demo_req: 'Demo İste',
        // Demo Page Additions
        demo_title: "Demo Talebi Oluşturun.",
        demo_subtitle: "CarboonIT yazılımı ile kurumsal karbon ayak izi hesaplama ve raporlama konularında şirketlere dijital pratik çözümler sunmaktadır. Demo talebinizi aşağıdaki formu doldurarak tamamlayın, size özel yazılımı satın almadan deneyimleyin.",
        demo_name: "Ad, Soyad",
        demo_company: "Şirket İsmi",
        demo_email: "Kurumsal E-Posta",
        demo_phone: "Kurumsal Telefon",
        demo_promo: "(Varsa) Kampanya Kodu",
        demo_service: "İlgilendiğiniz hizmet alanı?",
        demo_kvkk: "KVKK kapsamında aydınlatma metnini okudum, ilettiğim bilgilerin işlenmesini kabul ediyorum.",
        demo_etk: "ETK kapsamında aydınlatma metnini okudum, reklam ve duyurulardan haberdar olmak istiyorum.",
        demo_submit: "DEMO TALEBİ GÖNDER",
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('tr');

    const switchLanguage = (lang) => {
        setLanguage(lang);
    };

    const t = (key) => {
        return dictionary[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, switchLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
